### Base
#@base = http://192.168.0.164:3000
@base = http://192.168.0.165:3000
@canvas = http://192.168.0.174
@image = 3ec638c4-f069-41f4-9393-39cc60bca705_P.jpg

### START
GET {{base}}/playlist/start


//************************ Images ***************************//
### POST upload image
POST {{base}}/upload?orientation=P
Content-Type: application/octet-stream

< ./images/IMG_3187.jpeg

### GET image
GET {{base}}/images/{{image}}
Accept: image/jpeg

//***********************************************************//
//************************** CANVAS *************************//
//***********************************************************//
### GET settings
GET {{canvas}}/upstream/pull_settings

### SET settings with direct call from canvas
< {% request.variables.set("cron_time", new Date(Date.now()).toISOString().replace(/\.\d{3}Z$/, "Z")) %}
PUT {{canvas}}/upstream/pull_settings
Content-Type: application/json

{
  "upstream_on": true,
  "upstream_url": "{{base}}",
  "cron_time": null
}

